# Temporary hardware configuration for flake validation
# Replace this with actual hardware-configuration.nix generated by nixos-generate-config
{ config
, lib
, pkgs
, modulesPath
, ...
}: {
  imports = [ ];

  # Temporary boot configuration
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Temporary filesystem configuration
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  # RAID array placeholder
  # fileSystems."/mnt/storage" = {
  #   device = "/dev/md0";
  #   fsType = "ext4";
  # };

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
